version: 2
registries:
  cloudsmith:
    type: docker-registry
    url: https://docker.cloudsmith.io/
    username: "${{ secrets.CLOUDSMITH_USER_NAME }}"
    password: "${{ secrets.CLOUDSMITH_API_KEY }}"
    replaces-base: true

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - cloudsmith
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 11
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

